[package]
name = "nwserver_macros"
version = "0.1.0"
authors = ["Rink Springer <rink@rink.nu>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = [ "full" ] }
quote = "1.0"
proc-macro2 = "1.0"
