server_name = "BUCKET"
bindery_file = "bindery.toml"

[network]
ipx_network = 0x1234
internal_ipx_network = 0xdeadf00d
interface = "br0"

[volumes.sys]
path = "/opt/nwserver/SYS"
writeable = true

[users.supervisor]
initial_password = "HI"

[users.guest]

[groups.everyone]
members = [ "supervisor", "guest" ]
