server_name = "BUCKET"
bindery_file = "bindery.toml"

[unix]
# if set, changes to this user/group after startup
user = "rink"
group = "rink"

[login]
allowed = true
# mapped path when not logged in; can't access anything outside this path
visitor_root = "SYS:LOGIN"

[network]
ipx_network = 0x1234
internal_ipx_network = 0xdeadf00d
interface = "br0"

[volumes.sys]
path = "/opt/nwserver/SYS"
writeable = true

[users.supervisor]
initial_password = "HI"

[users.guest]

[groups.everyone]
members = [ "supervisor", "guest" ]
